# Generated by Django 4.2.6 on 2023-12-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultades.facultad')),
            ],
            options={
                'db_table': 'escuelas',
            },
        ),
    ]
