# Generated by Django 4.2.6 on 2024-01-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'estados_actividades',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'modalidades_actividades',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipos_actividades',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actividades')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.estado')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.modalidad')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.tipo')),
            ],
            options={
                'db_table': 'actividades',
            },
        ),
    ]
