# Generated by Django 4.2.6 on 2024-01-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponentes', '0003_alter_ponente_table'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='ponente',
            field=models.ManyToManyField(to='ponentes.ponente'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
    ]
