# Generated by Django 4.2.6 on 2024-01-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_alter_actividad_correo_alter_actividad_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='lugar',
            field=models.CharField(default='Por determinar', max_length=60),
        ),
    ]
