# Generated by Django 4.2.6 on 2024-01-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponente',
            name='correo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='profesion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
