# Generated by Django 4.2.6 on 2024-01-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponentes', '0002_alter_ponente_correo_alter_ponente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ponente',
            table='ponentes',
        ),
    ]
