# Generated by Django 4.2.6 on 2023-12-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
        ('documentos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(null=True)),
                ('fecha_recojo', models.DateField(null=True)),
                ('fecha_devolucion', models.DateField(null=True)),
                ('fecha_devolucion_confirmada', models.DateField(null=True)),
                ('estado_prestamo', models.CharField(choices=[('RESERVADO', 'Reservado'), ('PRESTADO', 'Prestado'), ('DEVUELTO', 'Devuelto')], default='RESERVADO', max_length=10)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.documento')),
                ('inventario', models.ManyToManyField(to='inventarios.inventario')),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
    ]
