# Generated by Django 4.2.6 on 2023-12-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='documento',
        ),
    ]
