# Generated by Django 4.2.6 on 2024-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_remove_prestamo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_confirmada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
