# Generated by Django 4.2.6 on 2023-11-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0001_initial'),
        ('idiomas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_documentos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=13)),
                ('anio_publicacion', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='documentos')),
                ('cantidad', models.IntegerField()),
                ('autor', models.ManyToManyField(to='autores.autor')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomas.idioma')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipo')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
    ]
