# Generated by Django 4.2.6 on 2023-12-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_documentos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13)),
                ('anio_publicacion', models.DateField()),
                ('descripcion', models.TextField()),
                ('cod_barras', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='documentos')),
                ('autor', models.ManyToManyField(to='autores.autor')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
    ]
