# Generated by Django 4.2.6 on 2023-12-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
