# Generated by Django 4.2.6 on 2024-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='documentos'),
        ),
    ]
